### ISSUE TITLE
Images dans le README.md

### ISSUE THREAD

**Issue by Nico207** [PeredurOmega/FrenchTravelCertificate#3]
Bonjour et bravo pour l'application: très bon design et code très propre.

J'ai une petite remarque concernant les images affichées dans le README : leur poids est beaucoup trop important (plusieurs Mo). Sur des petites connexions, c'est un peu la misère à afficher 😁

Je te propose l'optimisation suivante :
- afficher dans le Readme des images en 288x512
- mettre un lien sur ces images vers l'image d'origine, qui elle pourra être plus imposante

**Exemple**
`<a href="https://framapic.org/Vose5z00pmTU/ohMaL2g9eTd2.png"><img src="https://framapic.org/5MwVQmvaPEQp/kUWS1X9MWHeY.png" alt="Mockup 1" width="288" height="512"></a>`

<a href="https://framapic.org/Vose5z00pmTU/ohMaL2g9eTd2.png"><img src="https://framapic.org/5MwVQmvaPEQp/kUWS1X9MWHeY.png" alt="Mockup 1" width="288" height="512"></a>

Les petites images ont une taille comprise entre 23Ko et 37Ko et les grandes, entre 300Ko et 1181Ko.

_Les liens suivants ne seront disponibles que quelques jours._

Les images en 288x512 optimisées :
 - https://framapic.org/5MwVQmvaPEQp/kUWS1X9MWHeY.png
 - https://framapic.org/hRZvBio0cg6K/qQbiYNHqXPA0.png
 - https://framapic.org/UlexAwByJqZ9/YRpMXNnnIniL.png
 - https://framapic.org/1q3ldoal8PRH/0yg4I7GTBRRD.png
 - https://framapic.org/GSC6iwrK1xFA/nWJ13vJdp06f.png
 - https://framapic.org/Ddr9MRz0dpAa/bCbsGraQSxnD.png
 - https://framapic.org/mYfrWQNDl49r/hcWACsyQdQrc.png
 - https://framapic.org/qXP9wdvtecHc/hvGznMyT1kUQ.png

Les images non réduites (1728x3072), mais optimisées :
 - https://framapic.org/Vose5z00pmTU/ohMaL2g9eTd2.png
 - https://framapic.org/p46Tl64QM4Ht/PaDduK0e07Tv.png
 - https://framapic.org/SCZ8kgAIsJqM/GBeczJw7Wrme.png
 - https://framapic.org/IYKfqhNidLop/vKbPQs1Y8oqy.png
 - https://framapic.org/x3goy1FVKMAA/sRvGfAIBpxLH.png
 - https://framapic.org/Z7rDXwPlfyoh/Mtp6ijGbPlE9.png
 - https://framapic.org/M5mrjCzkYARr/0KHf3uLkeToS.png
 - https://framapic.org/yaMx4rQHZTFM/eBhIcbEpsjlQ.png

**Comment by PeredurOmega** [comment]
Merci pour ton retour, j'avais oublié de redimensionner les images (bon elles ne sont toujours pas aussi petites qu'elles pourraient l'être mais désormais elles font moins de 100 ko chacune). Ça m'était un peu sortie de la tête... Bref merci de me l'avoir rappelé. En plus elles n'étaient plus tout à fait à jour.
