### ISSUE TITLE
Identification colorée des profils

### ISSUE THREAD

**Issue by mobyFrag** [PeredurOmega/FrenchTravelCertificate#4]
Un grand merci pour ta création que j'utilise tous les jours !! Application propre, rapide et efficace ;-)
Voici une suggestion propre à mon contexte : je peux être confiné dans différents lieux (chez famille, couple, solo, etc.), du coup je me suis créé plusieurs profils, mais ils ont bien sûr tous le même nom (moi).
Ma demande est donc : pour chaque profil, pouvez-vous ajouter le choix d'une couleur à associer ? Ainsi, lors de la génération d'une attestation, je sais quel profil choisir sans doute possible. :)

Je suggère une couleur, même si une icône serait plus efficace, pour éviter d'allourdir l'app !

**Comment by PeredurOmega** [comment]
Merci de votre retour. Le problème m'a deja été remonté par d'autres personnes. Et en discutant nous en avions conclu que rajouter un numéro d'identification à chaque profil en cas d'égalité en terme de nom serait plus simple / efficace. Que pensez-vous de cette solution ? 

PS: en attendant la prochaine mise à jour, pour distinguer deux profils je vous invite à en créer un avec le nom tout en majuscule et pas l'autre.

**Comment by mobyFrag** [comment]
Très bonne idée aussi, le numéro d'identification !
Merci d'avoir lu.

**Comment by PeredurOmega** [comment]
Pas de problème. Cette fonctionnalitée sera implémentée très prochainement étant donné qu'elle ne nécessite pas de changements majeurs.

**Comment by PeredurOmega** [comment]
Fixed with c19f45d71574853f6b275ad0a9ea84e65bed186e
