### ISSUE TITLE
Retirer un clic du workflow de création d'attestation

### ISSUE THREAD

**Issue by mobyFrag** [PeredurOmega/FrenchTravelCertificate#5]
Hello ! 
Voici une nouvelle requête : à chaque création d'une attestation, nous devons en choisir le motif. A chaque sélection d'un motif, la description du motif apparaît et nous devons "Choisir" (à nouveau) pour passer à l'étape suivante.

Ma proposition : est-ce qu'un zone (la moitié, les 3/4 ?) du bouton d'un motif nous permettrait de passer directement à l'étape suivante ?

Merci !

**Comment by PeredurOmega** [comment]
Merci de votre retour. Pour résoudre ce problème, je pensais rajouter une option "Ne pas afficher la description des motifs" dans les paramètres. Ainsi au clic sur le motif ce dernier serait directement sélectionné sans afficher la description. Cette solution vous conviendrait-elle ?

**Comment by mobyFrag** [comment]
Très bonne idée !
Sinon je pensais également à la possibilité d'un clic long / clic court pour 2 comportements différents. Le paramètre est certainement une option plus propre.

**Comment by PeredurOmega** [comment]
Oui je pense que les paramètres permettront aux utilisateurs les moins aguerris de ne pas être déroutés par une telle fonctionnalité tout en offrant la possibilité à ceux qui le souhaitent d'aller un peu plus vite.

**Comment by PeredurOmega** [comment]
Fixed with 6482666a1ad292d98ba55a9a06748ecb0b70906b
