### ISSUE TITLE
Doc joint 

### ISSUE THREAD

**Issue by jbe2021** [PeredurOmega/FrenchTravelCertificate#6]
Bonjour
L'appli est super.

Il faudrait pouvoir joindre les autres attestations permanentes (professionnelle, scolaire) pour retrouver tous les pdf sur la même application 

Julie

**Comment by PeredurOmega** [comment]
Bonjour,

Merci de votre retour. C'est une bonne idée, j'essaierai de trouver du temps pour l'implémenter ce week-end.

**Comment by PeredurOmega** [comment]
Bonjour,

Finalement j'ai juste eu le temps de travailler sur ce sujet deux heures ce soir. 

J'ai presque terminé mais pas tout à fait. Je vais essayer de finir dans la semaine. Je vous tiens au courant.

**Comment by PeredurOmega** [comment]
Fixed with 4c612eee6fdfc324d6fdc3f2767251e2e273b52f. The app now handles custom documents (images + PDF). The update is being reviewed by Google and should be deployed in a few hours.
